remove all azure extensions to prevent stale results; tweak results processing

diff --git a/jobs/arc-conformance/conformance-spec b/jobs/arc-conformance/conformance-spec
--- a/jobs/arc-conformance/conformance-spec
+++ b/jobs/arc-conformance/conformance-spec
@@ -18,13 +18,11 @@ function juju::bootstrap::before
 {
     # azure-cli
     which az || sudo apt-get install -qyf azure-cli
-    az version || exit 1
-    az extension remove --name connectedk8s || true
-    az extension remove --name k8sconfiguration || true
-    az extension remove --name k8s-configuration || true
+    rm -rf ${HOME}/.azure/cliextensions/*
     # NB: can't get to az extension index, so install the bundled extensions
     az extension add -y --source ./jobs/arc-conformance/connectedk8s-1.0.0-py3-none-any.whl --pip-proxy http://squid.internal:3128
     az extension add -y --source ./jobs/arc-conformance/k8s_configuration-1.0.0-py3-none-any.whl --pip-proxy http://squid.internal:3128
+    az version || exit 1
 
     # helm
     which helm || sudo snap install helm --classic
@@ -102,15 +100,20 @@ function test::capture
     RESULT_SRC="plugins/azure-arc-conformance/sonobuoy_results.yaml"
     RESULT_DST="CharmedKubernetes_${CK_VERSION}_results.yaml"
     tar -xf artifacts.tar.gz ${RESULT_SRC}
-    cat ${RESULT_SRC}
 
-    if grep -q 'failed' ${RESULT_SRC}; then
-        echo "Failed conformance; not uploading results to azure storageaccount"
-        is_pass="False"
+    if [ -e ${RESULT_SRC} ]; then
+        cat ${RESULT_SRC}
+        if grep -q 'failed' ${RESULT_SRC}; then
+            echo "Failed conformance; not uploading results to azure storageaccount"
+            is_pass="False"
+        else
+            echo "Passed conformance; uploading results to azure storageaccount"
+            az storage blob upload -c canonical-testresults --account-name canonicalarcci -f ${RESULT_SRC} -n ${RESULT_DST}
+            is_pass="True"
+        fi
     else
-        echo "Passed conformance; uploading results to azure storageaccount"
-        az storage blob upload -c canonical-testresults --account-name canonicalarcci -f ${RESULT_SRC} -n ${RESULT_DST}
-        is_pass="True"
+        echo "No conformance results"
+        is_pass="False"
     fi
     az logout
 }
