Optimize multiple charms being built by the same charmcraft container

diff --git a/jobs/build-charms.yaml b/jobs/build-charms.yaml
--- a/jobs/build-charms.yaml
+++ b/jobs/build-charms.yaml
@@ -105,6 +105,8 @@
             #!/bin/bash
             set -eux
 
+            . $WORKSPACE/cilib.sh
+            
             sudo chown -R jenkins:jenkins /var/lib/jenkins/.config/ || true
 
             IS_FORCE=""
@@ -113,6 +115,14 @@
             fi
 
             rm -rf "$WORKSPACE/charms" || true
+
+            # Cleanup old charmcraft containers
+            ci_lxc_delete "${JOB_NAME}"
+            
+            # Configure cleanup routine for exit
+            charmcraft_lxc="${JOB_NAME}-${BUILD_NUMBER}"
+            trap 'ci_lxc_delete $charmcraft_lxc' EXIT
+            ci_charmcraft_launch $charmcraft_lxc
 
             tox -e py38 -- python jobs/build-charms/charms.py build \
               --charm-list "$CHARM_LIST" \
